import { Inter } from "next/font/google";
import NavBar from "./ui/components/navbar/navbar";
import "./globals.css";
import { MyContextProvider } from "./context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="emerald">
      <body className={inter.className}>
        <NavBar />
        <MyContextProvider>{children}</MyContextProvider>
      </body>
    </html>
  );
}
